### ISSUE TITLE
Consider exploring the haugene transmission-openvpn image

### ISSUE THREAD

**Issue by izaac** [EdyTheCow/docker-media-center#7]
I was able to use this image to add VPN support in my setup. I am using a proxy too to able to access the container because it isn't directly available. 

I feel the proxy a bit clunky as it keeps timing out. But as long as it does the job I'm good, perhaps someone with more time can tune it better than me.

```yaml
  transmission:
    image: haugene/transmission-openvpn:latest
    restart: unless-stopped
    networks:
      - global
      - local
    cap_add:
      - NET_ADMIN
    environment:
      - TRANSMISSION_DOWNLOAD_DIR=/data/downloads/complete
      - TRANSMISSION_INCOMPLETE_DIR=/data/downloads/incomplete
      - PUID=${ENV_PUID}
      - PGID=${ENV_PGID}
      - TZ={TIMEZONE}
      - OPENVPN_PROVIDER=custom
      - OPENVPN_USERNAME=
      - OPENVPN_PASSWORD=
      - OPENVPN_CONFIG=node-xx.protonvpn.udp
      - LOCAL_NETWORK=172.19.0.0/16
    volumes:
      - ./protonvpn/:/etc/openvpn/custom/
      - ${SERVICES_DIR}/transmission:/config
      - ${DATA_DIR}/downloads:/downloads
    ports:
      - 51413:51413 # Torrent port TCP
      - 51413:51413/udp # Torrent port UDP
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dmc-transmission.rule=Host(`${SUB_DOMAIN_TRANSMISSION}.${DOMAIN}`)"
      - "traefik.http.routers.dmc-transmission.tls=true"
      - "traefik.http.services.dmc-transmission.loadbalancer.server.port=9091"
      - "traefik.http.routers.dmc-transmission.tls.certresolver=letsencrypt"
      - "traefik.docker.network=global"
      # Basic auth
      - "traefik.http.middlewares.dmc-auth.basicauth.usersfile=/.htpasswd"
      - "traefik.http.routers.dmc-transmission.middlewares=dmc-auth"

  transiproxy:
    image: haugene/transmission-openvpn-proxy 
    environment:
      - PUID=${ENV_PUID}
      - PGID=${ENV_PGID}
      - TZ={TIMEZONE}
    ports:
      - 8080:8080
    links:
      - transmission
    networks:
      - global
      - local
```
